apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: diplomatic-jade-ermine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: diplomatic-jade-ermine 
  name: diplomatic-jade-ermine
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: diplomatic-jade-ermine 
